// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://euonfdzqbugfljtfsrps.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1b25mZHpxYnVnZmxqdGZzcnBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5MTA1MDksImV4cCI6MjA0NjQ4NjUwOX0.giLSuICbnznEvCQClgdWw0BRLFMdxa4GbzGv_LdzSfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);